version: '3'

services:
  php-fpm:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./laravel-app:/var/www/html

  nginx:
    image: nginx:alpine
    volumes:
      - ./laravel-app:/var/www/html
      - ./nginx:/etc/nginx/conf.d/
    ports:
      - "8000:80"
